background_opacity 0.6

font_size 14.0
modify_font cell_height +8

scrollback_pager mcat
scrollback_lines 50000

cursor none
cursor_trail 1
cursor_trail_decay 0.001 0.4
cursor_trail_start_threshold 0
cursor_blink_interval 0.8 ease-in-out

pixel_scroll true

symbol_map U+E000-U+F8FF,U+F0000-U+FFFFF,U+100000-U+10ffff Symbols Nerd Font Mono

# # BEGIN_KITTY_FONTS
font_family      family='Maple Mono' style=Regular features='calt cv43 cv10 cv42'
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

map ctrl+shift+w no_op
